apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-health-pipeline
spec:
  workspaces:
    - name: shared-workspace
  resources:
  - name: patientui-git
    type: git
  - name: patientui-image
    type: image
  - name: adminui-git
    type: git
  - name: adminui-image
    type: image
  - name: analytics-git
    type: git
  - name: analytics-dataservice-image
    type: image
  - name: analytics-webapp-image
    type: image
  tasks:
  - name: fetch-patientui
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
      - name: output
        workspace: shared-workspace
    params:
      - name: url
        value: https://github.com/IBM/node-s2i-openshift
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
  - name: build-patientui
    taskRef:
      name: s2i-nodejs
    runAfter:
      - fetch-patientui
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./site"
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/example-health/patientui
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: fetch-adminui
    taskRef:
      name: git-clone
      kind: ClusterTask
    runAfter:
      - fetch-patientui
    workspaces:
      - name: output
        workspace: shared-workspace
    params:
      - name: url
        value: https://github.com/IBM/php-s2i-openshift
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
  - name: build-adminui
    taskRef:
      name: s2i-php
    runAfter:
      - fetch-adminui
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./src"
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/example-health/adminui
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: fetch-analytics
    taskRef:
      name: git-clone
      kind: ClusterTask
    runAfter:
      - fetch-adminui
    workspaces:
      - name: output
        workspace: shared-workspace
    params:
      - name: url
        value: https://github.com/IBM/example-health-analytics
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
  - name: build-analytics-dataservice
    taskRef:
      name: s2i-nodejs
    runAfter:
      - fetch-analytics
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./data-service"
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/example-health/analytics-dataservice
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: build-analytics-webapp
    taskRef:
      name: s2i-nodejs
    runAfter:
      - fetch-analytics
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./web"
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/example-health/analytics-webapp
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: deploy-patientui
    taskRef:
      name: openshift-client
    runAfter:
      - build-patientui
    params:
    - name: ARGS
      value:
        - "new-app"
        - "patientui"
  - name: deploy-ol
    taskRef:
      name: openshift-client
    params:
    - name: ARGS
      value:
        - "new-app"
        - "ykoyfman/ol-example-health"
  - name: deploy-adminui
    taskRef:
      name: openshift-client
    runAfter:
      - build-adminui
    params:
    - name: ARGS
      value:
        - "new-app"
        - "adminui"
  - name: deploy-analytics-dataservice
    taskRef:
      name: openshift-client
    runAfter:
      - build-analytics-dataservice
    params:
    - name: ARGS
      value:
        - "new-app"
        - "analytics-dataservice"
        - "-e"
        - "HOST_IP=analytics-dataservice-tekton-pipelines.[YOUR_CLUSTER_NAME_AND_HASH]-0001.us-east.containers.appdomain.cloud"
        - "-e"
        - "MONGODB=[MONGO_CREDS]"
        - "-e"
        - "SCEME=http"
        - "-e"
        - "MAPBOX_ACCESS_TOKEN=[YOUR_MAPBOX_TOKEN]"
        - "-e"
        - "DATA_SOURCE_API=ol-example-health-tekton-pipelines.[YOUR_CLUSTER_NAME_AND_HASH]-0001.us-east.containers.appdomain.cloud/resources/v1/"
  - name: deploy-analytics-webapp
    taskRef:
      name: openshift-client
    runAfter:
      - build-analytics-webapp
    params:
    - name: ARGS
      value:
        - "new-app"
        - "analytics-webapp"
        - "-e"
        - "DATA_SERVER=http://analytics-dataservice-tekton-pipelines.[YOUR_CLUSTER_NAME_AND_HASH]-0001.us-east.containers.appdomain.cloud"
        - "-e"
        - "MAPBOX_ACCESS_TOKEN=[YOUR_MAPBOX_TOKEN]"
  - name: expose-ol-example-health
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-ol
    params:
    - name: ARGS
      value:
        - "expose"
        - "svc/ol-example-health"
  - name: expose-patientui
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-patientui
    params:
    - name: ARGS
      value:
        - "expose"
        - " svc/patientui"
  - name: expose-adminui
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-adminui
    params:
    - name: ARGS
      value:
        - "expose"
        - "svc/adminui"
  - name: expose-analytics-dataservice
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-analytics-dataservice
    params:
    - name: ARGS
      value:
        - "expose"
        - "svc/analytics-dataservice"
        - "--port=3000"
  - name: expose-analytics-webapp
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-analytics-webapp
    params:
    - name: ARGS
      value:
        - "expose"
        - "svc/analytics-webapp"
        - "--port=4000"
